name: Build and Deploy


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18


      - name: Create .env file and log variables
        run: |
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_SUPABASE_API_ENDPOINT }}" >> .env
          echo "NEXT_PUBLIC_PROJECT_REF=${{secrets.NEXT_PUBLIC_PROJECT_REF}}" >> .env
          echo "NEXT_PUBLIC_ADMIN_EMAIL=${{secrets.NEXT_PUBLIC_ADMIN_EMAIL}}" >> .env
          echo "NEXT_PUBLIC_PASSWORD_HASH=${{secrets.NEXT_PUBLIC_PASSWORD_HASH}}" >> .env


      - name: Debug Environment Variables
        run: env


      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_SUPABASE_API_ENDPOINT }}" >> .env
          echo "NEXT_PUBLIC_PROJECT_REF=${{secrets.NEXT_PUBLIC_PROJECT_REF}}" >> .env
          echo "NEXT_PUBLIC_ADMIN_EMAIL=${{secrets.NEXT_PUBLIC_ADMIN_EMAIL}}" >> .env
          echo "NEXT_PUBLIC_PASSWORD_HASH=${{secrets.NEXT_PUBLIC_PASSWORD_HASH}}" >> .env

      - name: Install dependencies
        run: yarn install


      - name: Build Next.js project
        run: yarn build
        env:
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_SUPABASE_API_ENDPOINT }}
          NEXT_PUBLIC_PROJECT_REF: ${{secrets.NEXT_PUBLIC_PROJECT_REF}}
          NEXT_PUBLIC_ADMIN_EMAIL: ${{secrets.NEXT_PUBLIC_ADMIN_EMAIL}}
          NEXT_PUBLIC_PASSWORD_HASH: ${{secrets.NEXT_PUBLIC_PASSWORD_HASH}}
          
      - name: Upload static site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-artifact
          path: out


  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-artifact
          path: out


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          keep_files: true
